name: Release action
description: Releases an action in a consistent way to be used across action repos
inputs:
  github-token:
    description: The github token used to push release tags
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: Bump version and push tag
      id: bump-version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        RELEASE_BRANCHES: main
        WITH_V: true
    - name: Get major version
      id: major-version
      shell: bash
      run: |
        echo "::set-output name=major-version-tag::$(cut -d . -f 1 <<< ${{steps.bump-version.outputs.new_tag}})"
    - name: Remove major tag
      shell: bash
      run: |
        git tag -d ${{ steps.major-version.outputs.major-version-tag }}
    - name: Push major tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CUSTOM_TAG: ${{ steps.major-version.outputs.major-version-tag }}
        WITH_V: true
