name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - action.yaml
jobs:
  release-action:
    runs-on: ubuntu-latest
    steps:
      - name: Release action
        uses: atomicfi/action-release-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
