name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - action.yaml
jobs:
  release-action:
    steps:
      - name: Release action
        uses: atomicfi/action-release-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
