name: Release #
on:
  pull_request:
    types:
      - closed
    branches:
      - feat-major-tag-test
jobs:
  release-action:
    runs-on: ubuntu-latest
    steps:
      - name: Release action
        uses: atomicfi/action-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
